Repository AY2324S1-CS2103T-T17-1/tp, pull requests merged in 2023-11, with the labels that each got.

#124 Update UI Elements
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: type.Enhancement, priority.High, severity.Medium

#123 Add View Command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/TaskWiseParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Note.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: type.Enhancement, priority.Medium

#128 Some fixes for view command
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/test/java/seedu/address/logic/parser/TaskWiseParserTest.java
Labels: priority.High

#129 Update Sort Parameter Parsers
  src/main/java/seedu/address/logic/sort/enums/SortOrderEnum.java
  src/main/java/seedu/address/logic/sort/enums/SortTypeEnum.java
Labels: severity.Medium

#131 Fix Unresponsive UI
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
Labels: type.Bug, severity.High

#130 UI-fix
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
Labels: type.Bug, priority.Medium, severity.Low

#127 Feature add command for deadline
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/task/Description.java
  src/main/java/seedu/address/model/task/Priority.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonTaskWiseStorageTest/invalidAndValidTaskTaskWise.json
  src/test/data/JsonTaskWiseStorageTest/invalidTaskTaskWise.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TaskWiseParserTest.java
  src/test/java/seedu/address/model/TaskWiseTest.java
  src/test/java/seedu/address/model/task/NameTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: priority.High

#132 Add status label back
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
Labels: type.Enhancement, priority.Medium, severity.Low

#133 Fix bug where view does not work
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High

#134 Fix overflow description bug when description is long
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
Labels: type.Bug, priority.High

#135 Fix Overflowing Member List
  src/main/java/seedu/address/ui/TaskCard.java
Labels: type.Bug, priority.High, severity.High

#139 Amend types of member names that are valid
  src/main/java/seedu/address/model/tag/Member.java
  src/test/java/seedu/address/model/tag/MemberTest.java
Labels: priority.High

#142 Remove AB3 links from index.md
  docs/index.md
Labels: priority.High

#144 Change error message when deadline inputs are wrongly formatted
  src/main/java/seedu/address/model/task/Deadline.java
Labels: priority.High

#145 Change All Occurrences of "Task Name" to "Task Description"
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/sort/SortUtil.java
  src/main/java/seedu/address/logic/sort/enums/SortTypeEnum.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/sort/enums/SortTypeEnumTest.java
Labels: severity.Low

#143 Fix TaskCard Selection Bug and ESCAPE Clearing Side Panel Bug
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/CommandBox.fxml
Labels: type.Bug, priority.Medium

#146 Fix comments to mention TaskWise
  src/main/java/seedu/address/model/task/Deadline.java
Labels: priority.Low

#147 Update user guide
  docs/UserGuide.md
Labels: priority.High, severity.Low

#148 Update user guide
  docs/UserGuide.md
Labels: type.Enhancement, priority.High

#140 Update User Guide
  docs/images/Ui.png
  docs/images/user_guide/AddAfter.png
  docs/images/user_guide/AddBefore.png
  docs/images/user_guide/AddCommandParam.png
  docs/images/user_guide/ClearAfter.png
  docs/images/user_guide/ClearBefore.png
  docs/images/user_guide/ClearCommandParam.png
  docs/images/user_guide/DeleteAfter.png
  docs/images/user_guide/DeleteBefore.png
  docs/images/user_guide/DeleteCommandParam.png
  docs/images/user_guide/EditAfter.png
  docs/images/user_guide/EditBefore.png
  docs/images/user_guide/EditCommandParam.png
  docs/images/user_guide/FindAfter.png
  docs/images/user_guide/FindBefore.png
  docs/images/user_guide/FindCommandParam.png
  docs/images/user_guide/GUI_Interface.png
  docs/images/user_guide/GUI_Interface_Annotated.png
  docs/images/user_guide/HelpCommandParam.png
  docs/images/user_guide/Help_After.png
  docs/images/user_guide/Help_Before.png
  docs/images/user_guide/ListAfter.png
  docs/images/user_guide/ListBefore.png
  docs/images/user_guide/ListCommandParam.png
  docs/images/user_guide/MarkAfter.png
  docs/images/user_guide/MarkBefore.png
  docs/images/user_guide/MarkCommandParam.png
  docs/images/user_guide/NoteCommandParam.png
  docs/images/user_guide/SortAfter.png
  docs/images/user_guide/SortBefore.png
  docs/images/user_guide/SortCommandParam.png
  docs/images/user_guide/Tutorial_After.png
  docs/images/user_guide/Tutorial_Before.png
  docs/images/user_guide/Tutorial_Clear_After.png
  docs/images/user_guide/Tutorial_Clear_Before.png
  docs/images/user_guide/Tutorial_Mark_After.png
  docs/images/user_guide/Tutorial_Mark_Before.png
  docs/images/user_guide/UnmarkAfter.png
  docs/images/user_guide/UnmarkBefore.png
  docs/images/user_guide/UnmarkCommandParam.png
  docs/images/user_guide/ViewAfter.png
  docs/images/user_guide/ViewBefore.png
  docs/images/user_guide/ViewCommandParam.png
Labels: type.Task, priority.High

#150 Update to UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/ui/TaskListPanel.java
Labels: severity.Medium

#180 Add credits for code reuse
  src/main/java/seedu/address/ui/TaskListPanel.java
Labels: type.Task

#182 Fix typos and hyperlink errors in UG
  docs/UserGuide.md
Labels: priority.High

#183 Triage - Fix Broken Links and Images in User Guide
  docs/UserGuide.md
  docs/images/user_guide/ViewAfter.png
  docs/images/user_guide/ViewBefore.png
Labels: type.Bug, severity.Low

#184 Improve Index.md and AboutUs.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/index.md
Labels: type.Bug, severity.Low

#185 Fix hyperlink bug under tutorial
  docs/UserGuide.md
Labels: priority.High

#194 Update Documentations and Diagrams
  README.md
  docs/diagrams/SortActivityDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/index.md
Labels: type.Task

#190 Add diagrams for add, clear, delete (DG)
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ClearSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/ClearSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
Labels: type.Task, priority.High, severity.Medium

#189 Add activity and sequence diagram for edit command members
  docs/diagrams/AssignSequenceDiagram.puml
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/XYZSequenceDiagram.puml
  docs/images/AssignSequenceDiagram.png
  docs/images/EditCommandActivityDiagram.png
  docs/images/XYZSequenceDiagram.png
Labels: priority.High, severity.Low

#191 Update maypfv PPP
  docs/team/maypfv.md
Labels: type.Task, priority.Low

#193 Update PPP of Sean
  docs/team/seantehds.md
Labels: priority.Medium

#192 Update priority prefix duplicate check and clear command message
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Bug, priority.High, severity.High

#187 Add sequence and activity diagrams for view and note
  docs/UserGuide.md
  docs/diagrams/NoteActivityDiagram.puml
  docs/diagrams/NoteSequenceDiagram.puml
  docs/diagrams/ViewActivityDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/NoteActivityDiagram.png
  docs/images/NoteSequenceDiagram.png
  docs/images/ViewActivityDiagram.png
  docs/images/ViewSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: type.Bug, priority.Low

#196 Branch DG diagrams
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/diagrams/MarkActivityDiagram.puml
  docs/diagrams/MarkSequenceDiagram.puml
  docs/diagrams/UnmarkActivityDiagram.puml
  docs/diagrams/UnmarkSequenceDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
  docs/images/MarkActivityDiagram.png
  docs/images/MarkSequenceDiagram.png
  docs/images/UnmarkActivityDiagram.png
  docs/images/UnmarkSequenceDiagram.png
Labels: priority.Medium

#197 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#199 Update UG, DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#200 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#201 Update UG and DG for 1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Low

#202 Update UG
  docs/UserGuide.md
  docs/images/user_guide/Tutorial_After.png
Labels: type.Task, priority.High

#204 Update images
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/exceptions/StorageExceptionDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/exceptions/StorageExceptionDiagram.png
Labels: type.Bug

#205 Fix UG and DG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UseCaseDiagram.puml
  docs/images/UseCaseDiagram.png
Labels: type.Task, severity.Low

#195 Update PPP Contributions
  docs/team/asdfghjkxd.md
Labels: type.Task

#203 Update DG mistakes and PPP
  docs/DeveloperGuide.md
  docs/team/jcsnap.md
Labels: severity.Medium

#206 Fix Formatting Errors
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, severity.Low

#209 Update DG
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High

#210 Fix UML Diagrams
  docs/diagrams/SortSequenceDiagram.puml
  docs/images/SortSequenceDiagram.png
Labels: severity.VeryLow

#211 Fix sequence siagram of note and view
  docs/DeveloperGuide.md
  docs/diagrams/NoteSequenceDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/NoteSequenceDiagram.png
  docs/images/ViewSequenceDiagram.png
Labels: priority.Medium

#212 Fix minor error in DG
  docs/DeveloperGuide.md
Labels: priority.Low

#215 Update PPP based on V1.3
  docs/team/sebtey.md
Labels: priority.High

#218 Update PPP
  docs/team/asdfghjkxd.md
  docs/team/jcsnap.md
  docs/team/maypfv.md
  docs/team/seantehds.md
  docs/team/sebtey.md
Labels: type.Task

#222 Update maypfv PPP
  docs/team/maypfv.md
Labels: priority.Low

#225 Update formatting of PPP
  docs/team/jcsnap.md
  docs/team/seantehds.md
Labels: priority.High

#223 Fix DG bug in dates
  docs/DeveloperGuide.md
Labels: priority.High

#213 [WIP] Add handling of leap days to parser
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
Labels: priority.High

#221 Fix Documenation Bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/asdfghjkxd.md
  docs/team/jcsnap.md
  docs/team/maypfv.md
  docs/team/seantehds.md
  docs/team/sebtey.md
Labels: type.Task, priority.High, severity.Low

#227 Fix table of content in user guide and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug

#231 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#226 Tests for Code Coverage
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ReadOnlyTaskWise.java
  src/main/java/seedu/address/model/member/Member.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMember.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/exceptions/json/IllegalJsonMemberValueException.java
  src/main/java/seedu/address/storage/exceptions/json/IllegalJsonTagValueException.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/data/JsonSerializableTaskWiseTest/typicalTasksTaskWise.json
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/core/LogsCenterTest.java
  src/test/java/seedu/address/commons/core/VersionTest.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CliSyntaxTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/logic/sort/SortUtilTest.java
  src/test/java/seedu/address/logic/sort/enums/SortTypeEnumTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/TaskWiseTest.java
  src/test/java/seedu/address/model/member/MemberTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/task/PriorityTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMemberTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonTaskWiseStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task, priority.Medium

#234 Update Javadocs for some methods and classes
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/TaskWise.java
  src/main/java/seedu/address/model/member/Member.java
  src/main/java/seedu/address/model/task/Task.java
Labels: priority.High

#233 Improve code quality
  docs/team/asdfghjkxd.md
  docs/team/jcsnap.md
  docs/team/maypfv.md
  docs/team/seantehds.md
  docs/team/sebtey.md
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/sort/SortUtil.java
  src/main/java/seedu/address/logic/sort/enums/SortOrderEnum.java
  src/main/java/seedu/address/logic/sort/enums/SortTypeEnum.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/test/java/seedu/address/commons/core/LogsCenterTest.java
  src/test/java/seedu/address/logic/sort/SortUtilTest.java
  src/test/java/seedu/address/logic/sort/enums/SortOrderEnumTest.java
  src/test/java/seedu/address/logic/sort/enums/SortTypeEnumTest.java
Labels: type.Enhancement, severity.Low

#232 Add assertions to mark, unmark, deadline
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Deadline.java
Labels: priority.High

#238 Fix documentation bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#236 Refactor parse method in AddCommandParser
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: priority.High

#235 Update Project README.md
  README.md
Labels: type.Enhancement

#242 Update PPP
  docs/team/asdfghjkxd.md
  docs/team/jcsnap.md
  docs/team/maypfv.md
  docs/team/seantehds.md
  docs/team/sebtey.md
Labels: priority.Medium

#243 Update PPP with Contributions
  docs/team/asdfghjkxd.md
Labels: type.Task, severity.VeryLow

#244 Fix missing content page link
  docs/UserGuide.md
Labels: severity.VeryLow

#245 Change PPP
  docs/team/seantehds.md
Labels: priority.High

#246 Fix full stops
  docs/team/asdfghjkxd.md
Labels: severity.VeryLow

#248 Update logging messages
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High

#251 Final bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: priority.High

#253 Final bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#254 Fix User Guide Bugs
  docs/UserGuide.md
Labels: type.Bug, severity.Low
