Repository AY2324S1-CS2103T-T17-1/tp, pull requests merged in 2023-10, with the labels that each got.

#38 Add sebtey's skeletal PPP
  docs/AboutUs.md
  docs/team/sebtey.md
Labels: type.Task

#41 Update PPP
  docs/team/asdfghjkxd.md
Labels: type.Task

#40 Add PPP section for jcsnap
  docs/team/jcsnap.md
Labels: type.Task

#47 Update _config.yml
  docs/_config.yml
Labels: type.Task

#48 Update User Guide to fix bugs and add new content
  docs/UserGuide.md
Labels: type.Task, priority.Low

#49 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low

#59 Task status integration
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/model/task/StatusTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: priority.High

#58 Updated Add Feature and Other Minor Fixes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Enhancement, priority.High

#61 Updated to add Mark and Unmark commands
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskWiseParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaskWiseParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
  src/test/java/seedu/address/model/task/StatusTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: type.Enhancement, priority.High

#65 Removed Unused Tags and Classes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/IllegalCommandException.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Address.java
  src/main/java/seedu/address/model/task/Email.java
  src/main/java/seedu/address/model/task/Phone.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/exceptions/json/IllegalJsonAddressValueException.java
  src/main/java/seedu/address/storage/exceptions/json/IllegalJsonEmailValueException.java
  src/main/java/seedu/address/storage/exceptions/json/IllegalJsonPhoneValueException.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableTaskWiseTest/duplicateTaskTaskWise.json
  src/test/data/JsonSerializableTaskWiseTest/invalidTaskTaskWise.json
  src/test/data/JsonSerializableTaskWiseTest/typicalTasksTaskWise.json
  src/test/data/JsonTaskWiseStorageTest/invalidAndValidTaskTaskWise.json
  src/test/data/JsonTaskWiseStorageTest/invalidTaskTaskWise.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CliSyntaxTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/TaskWiseTest.java
  src/test/java/seedu/address/model/task/AddressTest.java
  src/test/java/seedu/address/model/task/EmailTest.java
  src/test/java/seedu/address/model/task/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/PhoneTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/UniqueTaskListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableTaskWiseTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Enhancement, priority.High

#62 Add new link to redirect users to user guide
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement, priority.Medium

#63 Fix the formatting issue of response
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
Labels: priority.Medium

#74 Change jar file name
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: priority.Medium

#73 Update PPP
  docs/team/asdfghjkxd.md
Labels: type.Task, priority.Medium

#80 Update PPP for JCSnap
  docs/team/jcsnap.md
Labels: priority.Low

#86 Update PPP after end of v1.2
  docs/team/seantehds.md
Labels: priority.Medium

#85 Add puml diagram and screenshot for Note Sequence Diagram
  docs/diagrams/NoteSequenceDiagram.puml
  docs/images/NoteSequenceDiagram.png
Labels: priority.Low

#83 Update documentation
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/team/maypfv.md
Labels: type.Task, priority.Low

#82 Seb ppp & dg
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/AssignSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/AssignSequenceDiagram.png
  docs/team/sebtey.md
Labels: priority.Low

#88 Update DeveloperGuide
  docs/DeveloperGuide.md
Labels: priority.Low

#76 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortClassDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/UseCaseDiagram.puml
  docs/diagrams/exceptions/CommandExceptionDiagram.puml
  docs/diagrams/exceptions/ParseExceptionDiagram.puml
  docs/diagrams/exceptions/RecognisableExceptionsDiagram.puml
  docs/diagrams/exceptions/StorageExceptionDiagram.puml
  docs/images/SortClassDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/UseCaseDiagram.png
  docs/images/exceptions/CommandExceptionDiagram.png
  docs/images/exceptions/ParseExceptionDiagram.png
  docs/images/exceptions/RecognisableExceptionsDiagram.png
  docs/images/exceptions/StorageExceptionDiagram.png
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/TaskWiseParser.java
  src/main/java/seedu/address/logic/sort/SortUtil.java
  src/main/java/seedu/address/logic/sort/enums/SortOrderEnum.java
  src/main/java/seedu/address/logic/sort/enums/SortTypeEnum.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/exceptions/StorageException.java
  src/main/java/seedu/address/storage/exceptions/json/IllegalJsonValueException.java
  src/main/java/seedu/address/storage/exceptions/storage/FileStorageLoadException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Task, priority.Medium

#91 Updates to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/GeneralClassDiagram.puml
  docs/diagrams/SortClassDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/exceptions/CommandExceptionDiagram.puml
  docs/diagrams/exceptions/StorageExceptionDiagram.puml
  docs/images/GeneralClassDiagram.png
  docs/images/SortClassDiagram.png
  docs/images/SortSequenceDiagram.png
  docs/images/exceptions/CommandExceptionDiagram.png
  docs/images/exceptions/StorageExceptionDiagram.png
Labels: type.Task

#92 Add Future Improvements to Sort
  docs/DeveloperGuide.md
Labels: type.Task

#93 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: priority.Low

#94 DG Refinement
  docs/DeveloperGuide.md
Labels: priority.Low

#95 Update DG Model Class Diagram
  docs/images/ModelClassDiagram.png
Labels: priority.Low

#78 Add deadline functionality to Tasks
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/parser/CliSyntaxTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: type.Story, priority.High

#79 Add Note Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskWiseParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/Note.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableTaskWise.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableTaskWiseTest/duplicateTaskTaskWise.json
  src/test/data/JsonSerializableTaskWiseTest/invalidTaskTaskWise.json
  src/test/data/JsonSerializableTaskWiseTest/typicalTasksTaskWise.json
  src/test/data/JsonTaskWiseStorageTest/invalidAndValidTaskTaskWise.json
  src/test/data/JsonTaskWiseStorageTest/invalidTaskTaskWise.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/TaskWiseParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/JsonSerializableTaskWiseTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskWiseBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.Medium

#97 Fix constructor and instantiation to include all fields
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: priority.High

#75 Implementation of Sort Feature
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/IllegalTaskStatusModificationException.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/sort/SortUtil.java
  src/main/java/seedu/address/logic/sort/enums/SortTypeEnum.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Description.java
  src/main/java/seedu/address/model/task/Status.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/exceptions/json/IllegalJsonNameValueException.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TaskWiseParserTest.java
  src/test/java/seedu/address/logic/sort/SortUtilTest.java
  src/test/java/seedu/address/logic/sort/enums/SortOrderEnumTest.java
  src/test/java/seedu/address/logic/sort/enums/SortTypeEnumTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/task/StatusTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: type.Enhancement, priority.High

#98 Update Deadline and Unit Tests
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/data/JsonSerializableTaskWiseTest/duplicateTaskTaskWise.json
  src/test/data/JsonSerializableTaskWiseTest/invalidTaskTaskWise.json
  src/test/data/JsonSerializableTaskWiseTest/typicalTasksTaskWise.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/sort/SortUtilTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Labels: type.Bug, priority.High, severity.High

#84 Priority of Task
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Priority.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/data/JsonSerializableTaskWiseTest/typicalTasksTaskWise.json
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/CliSyntaxTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/sort/SortUtilTest.java
  src/test/java/seedu/address/model/task/PriorityTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Enhancement, priority.High

#101 Implement Sort by Priority
  src/main/java/seedu/address/logic/sort/SortUtil.java
  src/main/java/seedu/address/model/task/Priority.java
  src/test/java/seedu/address/logic/sort/SortUtilTest.java
Labels: type.Enhancement

#113 Enable assertions
  build.gradle
Labels: type.Task, priority.Low

#104 Replace addressbook logo with taskwise logo
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/task_wise_logo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Enhancement, priority.Low

#114 UI enhancements for Priority, Status
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TaskListCard.fxml
Labels: type.Enhancement, priority.Medium, severity.VeryLow

#105 Add Member model
  docs/DeveloperGuide.md
  docs/diagrams/AssignSequenceDiagram.puml
  docs/images/AssignSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Member.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedMember.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/commands/MarkCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
  src/test/java/seedu/address/logic/parser/CliSyntaxTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/sort/SortUtilTest.java
  src/test/java/seedu/address/model/tag/MemberTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
Labels: priority.High, severity.Low

#117 UI Enhancements: Permanent Side Panels
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/images/tick.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: type.Enhancement, priority.High

#118 Modify Member Fields on UI
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: type.Enhancement, type.Bug, priority.High

#121 Allow Edit Command for Priority to None
  src/main/java/seedu/address/model/task/Priority.java
Labels: type.Enhancement, priority.Low

#119 Add Note to Edit Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
Labels: type.Enhancement, priority.Medium

#122 Clear right panel after every command
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.Medium
